export interface User
{
    //id: number,
    //role_id: number,
    //admin_id: number,
    name: string,
    surname: string,    
    //dni: string,
    email?: string,
    description?: string,
    image: string,
    password?:string,
    //email_verified_at: Date,
    // cellphone: string,
    // address: string,
    //second_address: string,
    //reputation: number,
    //state: boolean,
    //created_at: Date,
    //updated_at: Date,
    //deleted_at: Date,
    //country_id: number,
    //city_id: number,
    //vehicle_id: number
}
